[workspace]
authors = ["Karl Theodor Ruby <karl.ruby@tuta.com>"]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "mojo-create"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
run = "mojo run -I src -I ../mojo-window/src"

[dependencies]
mojo = ">=1.0.0,<2"
sdl3 = ">=3.4,<4"
